# -*- coding: utf-8 -*-
"""IgnacioFigueroa_009D

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFEKl-NLmC7SSe6nTN_n9ywqwxGGxWX4
"""

def ingresarNIF(c):
  matriz = np.empty(shape=(c, 7), dtype=('U', 50))
  for i in range(c):
    NIF=""
    while len(NIF) != 12:
      NIF = input(f"{i+1}.- Ingrese NIF (XXXXXXXX-###): ")
      Nombre = input("Ingrese el Nombre (minimo 8 caracteres): ")
      edad =""

      edad = input("Ingrese edad")

      PertenenciaUE =input("Pertenece a la Union Europea?: ")

      fechaNac = input("Fecha De Nacimiento (dd/mm/aa): ")
      Estado = input("Estado Conyugal: ")


    # Guardo los valores ingresados por el teclado a la matriz

    matriz[i,0] = NIF
    matriz[i,1] = Nombre
    matriz[i,2] = edad
    matriz[i,3] = PertenenciaUE
    matriz[i,4] = fechaNac
    matriz[i,5] = Estado
    print("\n **** Datos de", Nombre, " fueron guardados con exito ****\n")
  return matriz


def mostrarDatos(NIFBUSCAR, c, matrizNIF):
  for i in range(c):
    if matrizNIF[i,0] == NIFBUSCAR:
      print("NIF: ", matrizNIF[i,0])
      print("Nombre: ", matrizNIF[i,1])
      print("Edad: ", matrizNIF[i,2])
      print("Pertenece a la UE: ", matrizNIF[i,3])
      print("Fecha De Nacimiento ", matrizNIF[i,4])
      print("Estado Conyugal: ", matrizNIF[i,5])
  return

def certificados(NIF, certificado, matrizNIF):
  import random as rn
  for i in range(matrizNIF.shape[0]):
    print("\n\nEmisión de Certificados")
    if certificado == 1:
      print("Certificado de nacimiento")
      print("************************")
    elif certificado == 2:
      print("Todos los Datos")
      print("********************")
    else:
      print("\n NIF: ", NIF)



    for i in range(matrizNIF.shape[0]):
      if matrizNIF[i,0] == NIF:
        print("Nombre: ",matrizNIF[i,1])
    print("\n*********************************************************\n\n")

  return

def verificaNIFexiste(p,matrizNIF):
  for i in range(matrizNIF.shape[0]):
      if matrizNIF[i,0] == p:
        return True
  return False



# ******   Comienza el programa principal ******
#Defino las variables que usaré
import numpy as np
opcion = 0
cantidad = 0
a = ""
b = ""
p = ""
op = ""
p = ""
tipoCertificado = 0

while opcion !=4:
  print("\n\nOpciones disponibles...")
  print("1.- Grabar Datos")
  print("2.- Buscar Datos ")
  print("3.- Impresión de certificados")
  print("4.- Salir")
  a = input("\n Ingrese la opción deseada: ")
  try:
    opcion = int(a)
  except:
    opcion = 0

  if opcion == 1:
    b = input("Ingrese la cantidad de datos a guardar : ")
    try:
      cantidad = int(b)
    except:
      cantidad = 0

    if cantidad > 0:
      DatosNIF = ingresarNIF(cantidad)


  if opcion == 2 and cantidad > 0 :
    p = input("Ingrese el NIF a buscar: ")
    if verificaNIFexiste(p,DatosNIF):
      mostrarDatos(p, cantidad,DatosNIF )
    else:
      print("\n **** Este NIF no existe ****")


  if opcion == 3 and cantidad > 0:
    p = input("\n\n Ingrese el NIF a imprimir certificados: ")
    if verificaNIFexiste(p,DatosNIF): #no me dio el tiempo
      try:
        tipoCertificado = int(op)
      except:
        tipoCertificado = 0
      if tipoCertificado != 0:
        certificados(p, tipoCertificado, DatosNIF)
    else:
      print("\n **** EL NIF NO EXISTE****")